# Generated by Django 6.0.3 on 2026-03-08 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheatSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('latex_content', models.TextField(blank=True, default='')),
                ('columns', models.IntegerField(default=2)),
                ('margins', models.CharField(default='0.5in', max_length=20)),
                ('font_size', models.CharField(default='10pt', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('latex_content', models.TextField()),
                ('default_columns', models.IntegerField(default=2)),
                ('default_margins', models.CharField(default='0.5in', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_latex', models.TextField()),
                ('answer_latex', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('cheat_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='api.cheatsheet')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='cheatsheet',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.template'),
        ),
    ]
