# Generated by Django 6.0.3 on 2026-04-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheatsheet',
            name='selected_formulas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
