# Generated by Django 6.0.4 on 2026-04-22 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_legacy_cheatsheet_owner(apps, schema_editor):
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split('.')
    user_model = apps.get_model(user_app_label, user_model_name)
    cheatsheet_model = apps.get_model('api', 'CheatSheet')
    db_alias = schema_editor.connection.alias

    username_field = getattr(user_model, 'USERNAME_FIELD', 'username')
    legacy_identifier = (
        'legacy-cheatsheets@example.com'
        if username_field == 'email'
        else 'legacy-cheatsheets'
    )

    user_lookup = {username_field: legacy_identifier}
    user_defaults = {'password': '!' }
    if username_field != 'email':
        user_defaults['email'] = 'legacy-cheatsheets@example.com'

    legacy_user, _ = user_model.objects.using(db_alias).get_or_create(
        **user_lookup,
        defaults=user_defaults,
    )

    cheatsheet_model.objects.using(db_alias).filter(user__isnull=True).update(
        user_id=legacy_user.pk
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cheatsheet_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(assign_legacy_cheatsheet_owner, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cheatsheet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheat_sheets', to=settings.AUTH_USER_MODEL),
        ),
    ]
