# Generated by Django 6.0.5 on 2026-05-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cheatsheet_content_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheatsheet',
            name='orientation',
            field=models.CharField(default='portrait', max_length=20),
        ),
    ]
