# Generated by Django 6.0.5 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_cheatsheet_orientation"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="selected_formulas",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
