# Generated by Django 6.1 on 2026-09-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_compile_quota_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilequotawindow',
            name='window_start',
            field=models.DateTimeField(db_index=True),
        ),
    ]
