# Generated by Django 6.1.1 on 2026-09-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_index_compile_quota_window_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheatsheet',
            name='generated_sections',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='generated_sections',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
