# Generated by Django 6.1.1 on 2026-09-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_cheatsheet_generated_sections_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestThrottleWindow',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('window_start', models.PositiveBigIntegerField(db_index=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
