# Generated by Django 6.1.1 on 2026-09-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_request_throttle_window'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestCompileBalance',
            fields=[
                ('identity', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('used', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('used__lte', 3)), name='guest_compile_max_three')],
            },
        ),
    ]
