services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: cheatsheet_db
      POSTGRES_USER: cheatsheet_user
      POSTGRES_PASSWORD: cheatsheet_pass
    # ports: comment out for now we'e not using atm
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.docker
    environment:
      - DATABASE_URL=postgres://cheatsheet_user:cheatsheet_pass@db:5432/cheatsheet_db
    volumes:
      - ./backend:/app
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 10s
      timeout: 5s
      retries: 10
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
volumes:
  postgres_data:
